# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RRFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.CharField(max_length=64)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=650)),
                ('useful', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matr_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='repetition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student'),
        ),
        migrations.AddField(
            model_name='repetition',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Subject'),
        ),
        migrations.AddField(
            model_name='break',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Student'),
        ),
        migrations.AddField(
            model_name='break',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena.Subject'),
        ),
    ]
